jn50view: Fix warning in saxhandler
Fixes following warning:
error: array subscript 4 is outside array bounds of 'const char16_t [1]'
   [-Werror=array-bounds]

The workaround uses an iterator instead of const char16_t *.